name: ci

on:
  push:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    # Run using Python 3.8 for consistency and aiohttp
    - name: Setup Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Setup Env
      run: pip install requests

    - name: Check Repo 
      run: |
        test -f README.md && rm README.md
        bash check.sh | tee README.md

    - name: Commit updates to README.md
      run: |
        rm -rf repos.json repos.txt
        git config user.name "dabao1955"
        git config user.email "dabao1955@163.com"
        git config --global --add safe.directory /github/workspace
        git add .
        git commit -am "Sync Repo Status on $(date)"

    - name: GitHub Push
      uses: ad-m/github-push-action@master
      with:
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
