name: ci

on:
  push:
  schedule:
    - cron: "0 0,6,12,18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    # Run using Python 3.8 for consistency and aiohttp
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Download Repos.json
      run: wget https://github.com/tiann/KernelSU/raw/main/website/docs/repos.json

    - name: Check Repo 
      run: |
        python3 check.py

